name: Trip_duration_predict
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - geographiclib=2.0
  - geopy=2.4.1
  - joblib=1.4.2
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - numpy==2.2.4
      - pandas==2.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
